language: node_js
node_js:
  - "node"
cache: yarn
os: osx
script:
  - 'cd $TRAVIS_BUILD_DIR/frontend && pwd && yarn appr'
  - 'cd $TRAVIS_BUILD_DIR/backend && chmod +x test.sh && ./test.sh'
after_success:
  - wget https://raw.githubusercontent.com/tripaloski/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - echo 'failed oops'
