language: node_js
node_js:
  - "node"
cache: yarn
os: osx
script:
  - 'cd $TRAVIS_BUILD_DIR/backend && chmod +x test.sh && ./test.sh'
  - 'cd $TRAVIS_BUILD_DIR/backend && ( echo "" ; echo "DISABLE_DEVELOPER_MODE = true" ) >> variables.env && npm install && npm install mocha -g && npm run test'
after_success:
  - wget https://raw.githubusercontent.com/tripaloski/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/tripaloski/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
